language: ruby
rvm:
 - 2.6.5
# uncomment and edit the following line if your project needs to run
# something other than `rake`:
# # script: bundle exec rspec spec

services:
  - postgresql

before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler

before_script:
  - psql -c 'create database webcomics_test;' -U postgres
