language: ruby

services:
  - postgresql

before_script:
  - psql -c 'create database webcomics_test;' -U postgres

before_install:
  - gem update --system
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler
